services:
  jobhuntly_fe:
    image: itrong0703/jobhuntly-frontend:latest
    container_name: jobhuntly_fe
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    env_file:
      - .env
    networks:
      - jobhuntly-network

networks:
  jobhuntly-network:
    external: true